### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by orenpapers** [expfactory/expfactory#117]
Hi,
I am trying to install and deploy expfactory on AWS.
I created a separate conda environment (with python 2.7) and followed the instructions (on MAC):
`pip install expfactory`
But when I try to run it:
`> expfactory --run --experiments stroop,nback
`
I get the error:
> usage: expfactory [-h] [--database {fllesystem,sqlite}]
>                   [--experiments EXPERIMENTS] [--subid SUBID] [--headless]
>                   [--no-random] [--base BASE] [--vars VARS] [--delim DELIM]
>                   {users,version,list,logs,install,build} ...

This happens also when I just enter the command:

`> expfactory`
Instead of opening a browser.
Any idea what the problem might be?

Thanks

**Comment by vsoch** [comment]
You are using the older (version 1) commands with the newer software. See https://expfactory.github.io/ for the updated commands. The newer version deploys experiment (reproducible) containers and the first is more of a templating system to create folders. Let me know if you have questions. Also, you will want to use python 3+.

**Comment by oren1k** [comment]
@vsoch Great thanks!
If I ran it using the quick start (docker run -p 80:80 vanessa/expfactory-experiments start) when can I find the data?

**Comment by orenpapers** [comment]
@vsoch Great thanks!
I can't see a possibility to run experiment using AWS or psiturk in this version - is it possible?

**Comment by vsoch** [comment]
You can run an experiment anywhere that supports running Docker containers. [See here](https://expfactory.github.io/usage) for different database options (the page walks you though it). The basic idea is that [you build a reproducible container](https://expfactory.github.io/generate#quick-start) first, and then run it.

Any experiment that is static html/css is fair game! You just need to install it.

**Comment by orenpapers** [comment]
@vsoch Thanks, the question I couldn't find an answer for is- Can I build a battery locally and send it somehow to someone else to execute, and get the results? Without him having to install a docker or anything else?

**Comment by vsoch** [comment]
If you package the experiment in a container, the container runtime is needed to run it. If you don't package the experiment in a container, then it's not reproducible.

**Comment by orenpapers** [comment]
@vsoch So if I want to send it to an "end user" he must install docker first in order to be able to run it?

**Comment by vsoch** [comment]
Oh no, not at all! Docker is a way to do deployment - meaning that you can develop on your local machine (and you would be best to have Docker!) but then deploy to any server or cloud provider that can support running a container. Your end user would go to some URL and enter a token to start your experiments, and the data is saved to either a database or the local file system of the server. For example, [here is a tutorial](https://expfactory.github.io/generate-https) that a user put together to deploy on Digital Ocean, and we also have users that have deployed their containers on servers hosted by local institutions. Does that make sense? The reason you want a container is so that when you publish your work, you publish the exact container that ran the experiments, and so if someone wanted to reproduce they could just run that container.

**Comment by orenpapers** [comment]
@vsoch Thanks! definitely make sense, I will go over it
