### ISSUE TITLE
not sure where to start

### ISSUE THREAD

**Issue by lsuemily** [expfactory/expfactory#13]
Hi! I'm reviewing these files, and it seems to have great promise, but I still think I am missing some very basic steps. For example, I have now installed Python 3.6.3. Do I need to try to run this through the Python interface, or the command prompt? I think I have some more learning to do to be able to catch up with you, but I'm trying :)

**Comment by vsoch** [comment]
hey @lsuemily I will help you! First your question - generally with python you can either run a script with the python interpreter, eg:

```
python myscript.py
```

or open up a terminal and run commands that you type, like on a command line:

```
 python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

In the case of expfactory, all of those are options, so that might just be confusing if you don't know the difference. For your use case, you don't need to know any python at all, because you interact with either executables or executables inside containers.

Now your use case - I think it is very common (Windows right?) and what we can do is wrap all of the python and other stuff inside of a container (called Docker) so you can just run it!

Do you want to for now get started learning about Docker? Here are some suggested steps:
 1. install it on your computer, and do the getting started tutorial https://docs.docker.com/get-started/
 2. give me a list of experiments from the (old legacy) experiment factory interface that you like

What I can do is package them up for you in the application, but have it built and served inside of a Docker container. As we do this I think you can start to get comfortable with container technologies - they are truly important for researchers. Does this sound like a reasonable plan?

**Comment by lsuemily** [comment]
Great! Will do. I'll start with Docker. I would like to start working with the digit span and spatial span tasks from the old interface. Thanks again for all of your help! I feel like I am learning so much, and that is really exciting.

Emily

**Comment by vsoch** [comment]
hey @lsuemily ! Just a heads up that I am almost done the Docker container, and I added the two experiments you were interested in this morning:

https://expfactory.github.io/experiments/

I might / should have something for you to test / walkthrough by end of weekend. I'm really glad that you are enjoying learning about docker, containers are so great! Here is one that is my favorite:

```
docker run godlovedc/lolcow
```
(run it more than once, lots of wisdom!)

Will keep you posted!

**Comment by lsuemily** [comment]
Great! Thanks! I appreciate your help so much @vsoch!

**Comment by vsoch** [comment]
hey @lsuemily I think we went as far as we could here, I'm going to close and please re-open if you need more help.

**Comment by lsuemily** [comment]
Thanks Vanessa- yes, I agree. Sorry it didn’t work out!

Emily
