### ISSUE TITLE
Forwarding to current port

### ISSUE THREAD

**Issue by tfeige91** [expfactory/expfactory#136]
Hi, 

I just tried running two sets of tests on the same server mapping to different ports: 

First: docker run -d -p 80:80 expfactory/experiments --database "DATABASE" --experiments code,simple-reaction-time,stroop,go-nogo,bart,n-back,tower-of-london,kirby,flanker,stop-signal,reversal-learning,judgement-of-line-orientation-test,information-sampling start

Second: docker run --name="impulsivity" -d -p 3391:80 expfactory/experiments --database "DATABASE" --experiments code,simple-reaction-time,flanker,go-nogo,kirby,stop-signal,bart,stroop,information-sampling,reversal-learning start

Basically it works good but if you start the tests the forwarding leads you to SERVER:80 not SERVER:3391. 
Is it possible to change that?

Thanks :)
Tim

**Comment by vsoch** [comment]
Hmm, so the way that it works is that when you build your experiment container, internally everything is being served via [port 5000](https://github.com/expfactory/expfactory/blob/master/expfactory/templates/build/docker/Dockerfile.template#L41), which is then proxy-ed to [port 80](https://github.com/expfactory/expfactory/blob/4744a05232bc3dd2050e6b9de2bc82b3e11d961e/script/nginx.gunicorn.conf) (or the same for [https](https://github.com/expfactory/expfactory/blob/4744a05232bc3dd2050e6b9de2bc82b3e11d961e/script/nginx.https.conf)). So I suspect that if you want a different port used instead of 80, you'd need to change the nginx configuration there. It might be easiest to add a step to your Dockerfile to add a custom one [e.g., see this step](https://github.com/expfactory/expfactory/blob/25468f7ff1615144213909248ac8cd54ae5405a3/expfactory/templates/build/docker/Dockerfile.template#L21) and then make sure that you expose the port, and definitely keep all your files in version control so you can reproduce your build.

And sorry for the confusion! I've transferred the issue to the correct repository. For some history, releases of expfactory through (I think) 2.5.47 or close to that were the original library, the one used for expfactory.org. The "version 2" of expfactory doesn't refer to 2.x, but to version 3.x and up (releases on pypi https://pypi.org/project/expfactory/). This is the one that builds containers for you with experiements.
