### ISSUE TITLE
Question - Stop condition when participant makes mistake

### ISSUE THREAD

**Issue by maranut** [expfactory/expfactory#137]
Hi to all! This is not an issue but rather a question from a beginner when it comes to Javascript.
I found the Digit Span task in your experiment library and was trying to adapt it so that the forward recall block would stop as soon as the participant incorrectly recalls a series of digits. After the mistake in the forward recall block, the participant would then proceed to the reverse part, and so on. I've tried quite a few things but I guess I am just not experienced enough in Javascript code to actually implement this correctly.
Maybe someone on here knows how to help?
Thanks so much in advance!

**Comment by vsoch** [comment]
hey @maranut ! Expfactory is sort of the infrastructure underlying running experiments - and we don't have enough staff to really give individual advice on changing JavaScript experiments. Specifically this repository is just maintained by me and I've long since left my graduate school lab, and Stanford as well. But - I can point you to places where you can ask for help!

 - The base of the experiments here is with jspsych, and there are various ways to ask for help there https://www.jspsych.org/about/support/.
 - Lab.js is another community with a lot of experiment folks - it would be worth joining their slack and asking for help https://lab.js.org/resources/support/
 - My previous lab is still maintaining experiments to some extent - I think it's unlikely you'll get a response but you can try on [this repo](https://github.com/expfactory/expfactory-experiments). The original developers of the javascript code I also think have left the lab.
 - You can also try twitter to ask for help, e.g., here is the [creator of Jspsych](https://twitter.com/joshdeleeuw?lang=en) that might be able to give you the right place to ask for help.

And a suggestion - if you fork the task and push your changes to your fork branch, and then you can include that diff along with your question, it's much more likely you will be helped.

**Comment by maranut** [comment]
Hi @vsoch ! Thank you for your quick reply and tips! Sorry, I didn't know you were the only one maintaining this repository and that this wasn't really "active" anymore. I asked my question in the jsPsych forum as well but unfortunately didn't get replies there either. But I figured out a work-around :)

**Comment by vsoch** [comment]
Sure thing! To give you a little history, the first version of expfactory was [expfactory-docker](github.com/expfactory/expfactory-docker) with [expfactory-python](github.com/expfactory/expfactory-python) that I developed with my lab as a graduate student, with my lab-mates doing most of the experiments and me the rest. That was deployed to expfactory.org (and used mturk) and was great for the lab, but it never scratched my itch because we couldn't open it up to the larger community. I made this version of expfactory, here, after I had graduated (and I'm the only developer for) and it uses a modular form of the original experiments in expfactory-experiments and is container based.

So the experiment software (e.g., lab.js/jspsych or other) is separate from the means to deploy it (expfactory). I do think my old lab has plans for a second version of the original expfactory.org (and they probably will name it something different) and I'd watch https://github.com/expfactory/expfactory-deploy if you are interested. But again, this is a separate thing from the underlying experiments. Since we created expfactory there have also been a lot of other options.

I would really try reaching out to the labjs community too (and trying labjs) because I've found them extremely friendly.
