### ISSUE TITLE
[feedback wanted] retake experiment option?

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory#40]

**Comment by vsoch** [comment]
If a user (without a token) returns to the interface and the session is preserved (same browser) he/she can retake the experiment. Given a token, this is also the case, and the results are re-written. Is this a suitable approach?

**Comment by earcanal** [comment]
I think this is going to be a "it depends".  Can you cover all cases by implementing tokens as having an expiry time?

*As a researcher, I want my (online) participant to complete the experiment within a maximum time period, and I want to know if they don't complete within than period in order to decide whether to issue them a new token.*

Use cases are hard.

**Comment by vsoch** [comment]
hey @earcanal when you have time to review the PR, I think this need is best met by a function I've provided to expire / invalidate a token. I'm working on the experiment robot containers today so I'll ping you later about that too!

**Comment by earcanal** [comment]
What sort of review do you want?  I don't think I understand the code well enough to do a proper code review.

**Comment by vsoch** [comment]
See the PR - I created images (containers) for you to test and use.
