### ISSUE TITLE
[JOSS Review] Installation instructions

### ISSUE THREAD

**Issue by oesteban** [expfactory/expfactory#55]
As per openjournals/joss-reviews#521:

> **Installation instructions**: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

Even though the project is well documented, I have the impression that the information could be very unclear to someone who does not know about docker or containers. I like the approach of let's dive in ASAP, but for unexperienced users that likely will hold them off jumping. Especially when other barriers come into play (e.g. you are not English native speaker, like myself), the documentation might be a bit overwhelming/discouraging.

A separate section where the documentation is more "traditional" (with clear steps and sections) would be very much appreciated. Or maybe a video clip showing how to run the containers *a la* datalad?

I don't think this is a major issue though, just trying to give a different point of view.

**Comment by vsoch** [comment]
hey @oesteban! This is a good point - the first set of instructions assume that the user understand / knows Docker, and if this isn't the case, it's a hard entry. I'm going to try adding a more direct link from the first page and the README to this page --> https://expfactory.github.io/expfactory/generate#detailed-start and then I can write a bit more about containers there. I'll add this to the current PR and let you know when it's ready for your review.

**Comment by vsoch** [comment]
okay, I've added a gentle introduction to both (containers and then using expfactory) to the PR. I intentionally have not shown the user how to install expfactory on the host because I want the primarily interaction to be via a builder container, so I am not showing the traditional `pip install` as you would expect with other Python software. In that the container is provided, the interaction with the software is best done via the container so users avoid the dependency issues that arise when trying to install native to the host.

**Comment by earcanal** [comment]
I would remove references to Singularity for now, or explain _very clearly_ how it fits into the (container) picture.  My understanding is that Docker is more stable than Singularity?  The consequence of that for me was that my understanding increased rapidly once I got my hands a bit grubby with Docker.

**Comment by vsoch** [comment]
good call @earcanal ! This is an artifact of the fact that I first implemented this entire thing with Singularity, and then changed my mind, haha. I agree that Docker turned out to be better suited, as it's optimized for web services (and this functionality is only starting development for Singularity). I updated the PR to remove these stale references. The only remaining are with regards to integrations (because there are Singularity containers for some of the other tools provided).

**Comment by vsoch** [comment]
Contributions are merged, thanks for the help!
