### ISSUE TITLE
[Feature Request] global and participant variables for experiments

### ISSUE THREAD

**Issue by Fethrblaka** [expfactory/expfactory#58]
I am programming an experiment that gives different questions to each user depending in the token they get. For this i need the experiment to know the users token without having to modify it before every run.
Is it feasible to do this, or, in some other way, allow the experiment to know the users token without having it ask the user?

**Comment by vsoch** [comment]
If a token corresponds with a set of questions (an ordering, for example) I would create each ordering as its own experiment, and then assign users (with the tokens) to the "different" experiments.

Could you walk me through the process of (what you do) to assign a token, map to an ordering, and then the logic (and implementation) in the experiment to do this? And how many orderings, how are they generated, etc.

**Comment by Fethrblaka** [comment]
The idea is for there to be only one experiment with a folder of modules and a .csv stating what modules have to be chossen for each question.
I would generate a list of token at the start of the study and assign them their experiment parameters (modules for each question) and put it together in the experiment folder. Then i would run the command for starting the battery in headless mode, input the token, and when it reaches the experiment, the users does not have to input anything, instead the experiments reads the initial token and display the questions.
The question would be formed by a context, a question, a response method and parameters for the context.

**Comment by vsoch** [comment]
ah ok! I think what might be useful (and cool!) would be to have an ability to define some set of parameters for an experiment, fed in from a flat file input as you mentioned. Then they would be input into the experiment in some format based on the token (user) and experiment likely as a url parameter, and up to the experiment to parse the url.

Are you able to share with me some dummy code for a simple experiment that runs and obtains some parameters from the url? I can start to think about this. A quick caveat - I'm having a major surgery tomorrow morning and I'm not going to be able to work on this for a few weeks. So there is no rush on the dummy code, and I will pick up on development after!

**Comment by Fethrblaka** [comment]
Here some javascript to parse the url and get all parameters in an object and an experiment [demo.tar.gz](https://github.com/expfactory/expfactory/files/1619468/demo.tar.gz), just add some parameters to the url, like `?token=123456&cat=cool`. Hope your surgery goes well :smiley:.

**Comment by vsoch** [comment]
hey @Fethrblaka I'm alive! (just kidding) I started to work on this, and first put the demo above into a repository with a Dockerfile for quick development and testing https://github.com/expfactory-experiments/test-parse-url . I started a bunch of thinking (just copy pasted it out of this window) because I want to get a little more verification first. I think the first thing you mention:

>> Then i would run the command for starting the battery in headless mode, input the token, and when it reaches the experiment, the users does not have to input anything

You are saying you could basically send the user a link to start with the token in the url, like `https://myexperiments.org?token=1234` and it would handle the logging in portion. Correct? If so, that makes sense!

And then (I think) what you want is for the token to act as a "lookup" for experiments. Meaning that, if I have parameters one, two, and three, I would have a csv file that defines them:

```
token,exp_id,one,two,three
12345,stroop,value1,value2,value3
```
and then when subject 12345 comes along and hits the stroop task, we look in our file, find the values, and pass them along:

```
https://myexperiments.org/experiments/stroop?one=value1&two=value2&three=value3
```
And then you can do whatever you like, I would assume, as long as you finish and send data to /save and then go to /next. Once the user has started the session, the token is saved in the session, so we wouldn't need it beyond the initial login. 

So here is how I've thought about this so far. The "start" of this image would likely need to have an argument to point to this data file:

```
docker run -p 80:80 vanessa/experiment start --vars variables.txt
```
and my worry here is having an experiment that requires some input variables, but then the user doesn't provide. What are your thoughts on both documenting the need, and having some kind of default fall back?

My other question is about how we can handle choosing from some variable list. I think we would handle this the same way but perhaps change the delimiter of the file. In fact, I might make tsv (tab separated) the default off the bat, so that you could have this:

```
token [ tab ] exp_id [ tab ] list_one                       [ tab ] varN 
12345 [ tab ] stroop [ tab ] value1,value2,value3 [ tab ] valueN
```
and the delimiter could also be exposed command line and environment, if necessary

```
docker run -p 80:80 vanessa/experiment start --vars variables.txt --delim ","
```
But do you think the text file way is the best way to go? How much of the variable definition should be pre-defined in the config vs. "just pipe in anything to the exp_id provided by the experimenter, and ensure the experiment has checks and balanced for defaults?"

My next question is about having vs. not having tokens. With a token, the assignment is logical. Without a token, I'm not sure. Should variables only be possible for token defined runs, **or** should there be some global identifier token that signifies "this is for global" and then would the order of operations be:

 - if the user has a token, and token is defined in variables file, use those
 - if user doesn't have token but global is defined, use those
 - if no user token and no global, no variables passed.

Could you elaborate more on this? It sounds more like an experiment-specific thing, and not for the infrastructure running it:

>> instead the experiments reads the initial token and display the questions. The question would be formed by a context, a question, a response method and parameters for the context.

**Comment by Fethrblaka** [comment]
Hi @vsoch, the idea was for the experiment to be set up with a list of tokens and their corresponding configuration beforehand, so the experiment would get the token from expFactory and search his configuration in a file contained in the experiment folder using the token. That way, an user could access the page and provide a valid token and the experiment would configure itself. 
The process of the creation of the tokens plus configuration file was to generate a set of tokens and assign them a configuration, then copy the file inside of the docker container.

What i ended doing instead of copying the configuration plus tokens file once, was copying every time a run starts only with the configuration for the token chosen. It limits the system to a subject for docker running but allows for more control.

The idea at the end was for the experiments to be able to tell a participant from another so, for example, if i want 10 participants to se test A and ten to see B i wouldn't have to make two different images.

**Comment by vsoch** [comment]
I understand this use case, do you have comments on the suggested route that I made? It would be flexible to support your use case, I think.

**Comment by Fethrblaka** [comment]
I like the idea of experimental factory handling user specific data for the experiments and giving it as needed, i think it should be the responsibility of each experiment to handle this variables or lack of them.
I don't like tough that all the variables would be visible to the subject, as it may clue them into something and alter the experiment.

**Comment by vsoch** [comment]
heyo @Fethrblaka apologies for the delay here! I'm going to put aside some time for this soon, just had a wave of todos that I'm coming out of. From your last comment, one thing that is clear I think (or will be challenging) is that given that we have to get the variables from the server into the experiment, I don't see how it would be entirely possible to make the variables not visible to the subject. I think the most logical thing to do would be to have states or settings set via the POST (e.g,. `?g=A`) that essentially look like goppelty gook, but then your javascript / experiment code handles the logic for what that means. Anyway, I'm going to start testing this out. Stay tuned!

**Comment by vsoch** [comment]
and something to think about - I was thinking of having a "catch all" in the case that the experimenter just wants to assign everyone being run at that time a set of variables for experiments. But what about some kind of use case where you would want to randomly select a participant for one of N groups? Either you could pre-determine the groups (not hard to do, implementation wise) or you would need to have some random selection happen at runtime. The danger here (what I'm worried about) is that if the user goes away and comes back, then there is a different group. So would the first option (that the experimenter defines the group) be a reasonable start, or do you have another idea in mind?

**Comment by Fethrblaka** [comment]
Hi @vsoch , you mean like having a third mode (that allows for anyone to participate in order to have the maximum amount of runs of the experiments). In that case it could be useful to randomly assign a group to the user and most possible problems, like a user rerunning a test should be taken into account by the experimenters. Otherwise, if you already have an amount of runs in mind, you should get that amount of tokens spread into the N groups and assign the tokens randomly to the users. having the randomizing on run time would only complicate things.

As a side note, my interest in this feature comes from my internship (that i just finished yesterday), so i no longer have such a close contact with the ones doing the actual experimenting and my opinions might not be so pertinent, but i am taking this as an unfinished part of the internship and will keep paying attention to this and providing (hopefully useful) feedback.

**Comment by vsoch** [comment]
hey @Fethrblaka congrats on finishing your internship! My thinking was a use case where I have an experiment with four orderings, and I don't care to assign particular people in advance but I want them generally put into one of the four. This might actually be bad practice to begin with, because it suggests that I don't keep track of who goes into what group, and if this is the case we should just nix that possibility and force the user to predefine any orderings and assigned users. What do you think?

**Comment by Fethrblaka** [comment]
I feel the same, can't really think of a use case for run time randomizing that isn't covered by other better options.

**Comment by vsoch** [comment]
hey @Fethrblaka ! I think the feature is ready for testing, take a look at #75 when you get a chance. Thanks again for helping out!
