### ISSUE TITLE
difficulty running anything on windows 7

### ISSUE THREAD

**Issue by amclarekelly** [expfactory/expfactory#59]
Hi there,

I should start by admitting that my understanding of docker is poor, so apologies if that's the main issue here.

I am trying to get two experiments (digit span and n-back) running on a lab laptop that runs Windows 7.

I managed to get docker installed and it seems to work ok. The problem seems to be at the point of building the container. Stuff *happens* but nothing is in the directory afterwards, and there is nothing visible via localhost. I've attached a screenshot of the docker window and the error I obtain at the end.
![issue](https://user-images.githubusercontent.com/33491894/34834605-5b54a378-f6ea-11e7-8541-f1242be1e706.PNG)

I also tried just running one of the pre-made containers, but get the error shown in issue2.
![issue2](https://user-images.githubusercontent.com/33491894/34834726-9da3fe0e-f6ea-11e7-8d0a-d5cac821452e.PNG)

Any help would be much appreciated!
Clare

**Comment by amclarekelly** [comment]
By the way, I can get the experiments I want working fine on my mac desktop, so I assume the issue is with this laptop. Thanks so much.
Clare

**Comment by rwblair** [comment]
Hi Clare,

From the last line of the second image theres an error "Bind for 0.0.0.0:80 failed: port is already allocated."

You might try stopping all running docker containers on your computer and try starting that particular container again. `docker ps -aq` will give you the IDs of all running containers that you can then run `docker stop <container id>` on. I believe docker stop can take a list of space separated IDs. If one of those running containers is using port 80 it will free it up for use again.

**Comment by amclarekelly** [comment]
Thanks @rwblair - I managed to stop all containers and reran the command. It appears to work correctly but when I go to http://127.0.0.1/ there's nothing. Thank you so much for your help, this is so frustrating!
![capture2](https://user-images.githubusercontent.com/33491894/34873225-1efd4734-f78c-11e7-9b7b-d71a186e8b2a.PNG)

**Comment by earcanal** [comment]
Looks like it's listening on port 5000.  Try http://127.0.0.1:5000.

**Comment by amclarekelly** [comment]
No luck with that either, unfortunately - same "This site can't be reached" error.
Clare

**Comment by vsoch** [comment]
hey @amclarekelly ! Apologies for the delay, I actually had a big surgery and am recovering, but they gave me my computer back, lol. 

What I think is happening is that *something* is using port 80, so the container starts and the flask server will run, but it's entirely behind this proxy thing so you won't see anything when you open the browser. So [follow these instructions](https://stackoverflow.com/questions/1960750/how-to-find-which-program-is-using-port-80-in-windows) to be absolutely sure there is nothing running on 80. If you find something (e.g., nginx or apache) there are [instructions for stopping](https://stackoverflow.com/questions/1960750/how-to-find-which-program-is-using-port-80-in-windows
).
- Then, just for the heck, it looks like you are going to 127.0.0.1? Try going to `0.0.0.0` and then `0.0.0.0:5000` 
- Try different browsers. Sometimes chrome stops working for me, but firefox is ok. 
- Next, try running in detached, and inspect the docker logs to look for any weirdness:

```
# Make sure nothing else running
docker ps
# should be nada
```
Then run the container in detached mode
```
docker run -d -p:80:80 vanessa/expfactory-experiments start
```

Then you can do docker ps to get the id, and then use `docker logs <id>` to see the container logs. 

If we don't know after that, then likely it's something to do with how the webby stuff is working with Docker on windows. As luck would have it, I will have access to a Windows machine in about a week! If you can replicate your installation of Docker (more detail better) I can try to recreate it and reproduce your bug. Thanks!

**Comment by amclarekelly** [comment]
Hi @vsoch, thank you so much for replying, especially after your surgery! I wish you a speedy recovery.

So it looks like perhaps the problem is the McAfee antivirus software? The screenshot below shows the ports and what's running. Process 1956 is McAfee.
![capture3](https://user-images.githubusercontent.com/33491894/34952313-3866dbe0-fa11-11e7-89fd-7ae9906b3615.PNG)

If you think that's the problem, hopefully stopping McAfee will work - but I haven't got the right privileges to try. Hopefully I will be able to do it tomorrow!

Thanks again for your help,
Clare

**Comment by amclarekelly** [comment]
Sorry - just to follow up, it's possible that I will not be able to get McAfee switched off as it may be a condition of being on the network in our college. If so, is there any other solution or work around? Thank you!

**Comment by vsoch** [comment]
I'm a bit shooting in the dark, but I would first try "enabling" that port (8081) via McAfee. Check out the [instructions here](https://service.mcafee.com/webcenter/portal/cp/home/articleview;jsessionid=YKL-bO9bVVcEZ3qnH3CI0_OwgIg9yy-pl62CmNXGfDaBLGa07Lc6!-192026955!24720336?articleId=TS100887&_afrLoop=642534914167856#!%40%40%3F_afrLoop%3D642534914167856%26articleId%3DTS100887%26centerWidth%3D100%2525%26leftWidth%3D0%2525%26rightWidth%3D0%2525%26showFooter%3Dfalse%26showHeader%3Dfalse%26_adf.ctrl-state%3Dyer2b6pff_4). If this is for your research, I think your server / computer tech admin should help you to figure out a solution. I'll keep thinking about workarounds... are you able and willing to use Docker? Docker might at least let you elevate to sudo and perhaps get around some of these issues :)

**Comment by amclarekelly** [comment]
Thanks @vsoch. This is what I've been told by our Tech: "I’ve confirmed with IT that the McAfee Endpoint Security installed on College computers does not include a firewall module, since there is a dedicated firewall around the College network. However, Windows firewall may be enabled on your machine. You could disable it, or create a rule allowing traffic on port 8081."

I will check the windows firewall (don't have laptop with me right now) but any other work arounds would be much appreciated. I am fairly ok with command line stuff if you have an idea of how to make this work with Docker.

Alternatively - this is really only for 2 tasks, n-back and digit span. Is there any way I could use them in the pre-docker form? Were they python based? Python is running on the machine and is working well for another experiment that relies on pyton and javascript.

Thank you again for all your efforts!
Clare

**Comment by earcanal** [comment]
If you're running your study locally you don't need Docker.  You can just download the task repo (e.g. [n-back](https://github.com/expfactory-experiments/adaptive-n-back)) and open `index.html` in a browser or serve `index.html` using a local python webserver (e.g. `python3 -m http.server 9999`).

**Comment by vsoch** [comment]
Yes that's the great thing about the experiments, they work statically and locally! @amclarekelly I think you will go far to disable the windows firewall. If there is some higher level process blocking (err "protecting") ports then using python on the local machine vs. Docker won't make much of a difference if the ports are blocked. @earcanal suggestion to run with python is right on, and I am (fingers crossed) hoping the disable of the Windows firewall may help too. The container approach is important for research because you can save your entire protocol (even if it's a bit small) via the container in your future publication, and have confidence it will reproduce. On the other hand, using python locally is likely to be ok, but down the road if someone installs a slightly different version of python and that command doesn't work (or some other dependency) then it's not as reproducible. But we are making progress, and in my mind getting the experiments running is the goal!

**Comment by earcanal** [comment]
This method of running locally is a great improvement on the (functional but hacky) shell script hack I still use to run local studies using the previous version of TEF.  Docker extends that small step with a giant leap!

(Just wanted to add this data point and interim thanks for the amazing work @vsoch has put in.)

**Comment by amclarekelly** [comment]
Thank you @earcanal and @vsoch. I will first try the windows firewall and see where we are at. If that still doesn't work, I will have to go with the local python-based run.

Regarding that - I downloaded the n-back task repo (I *really* need to learn github!!) and can run it no problem on my mac. But, I'm sorry to ask - how do I now specify a subject ID? I followed the instructions here [http://expfactory.readthedocs.io/en/latest/getting-started.html#local-deployment-of-experiments](url) but they appear to be outdate in that the expfactory commands don't worry (I get expfactory: error: too few arguments) when I do e.g., expfactory --run --experiments nback,digit --subid TEST01 from inside the directory that contains adaptive-n-back-master.

Thanks again for all your help.
Clare

**Comment by vsoch** [comment]
The docs you are linking to aren't for the release of expfactory that is represented at this repo (and we are discussing!) That was the original release that worked very differently. It was a good first shot but not good enough (hence why I made this container version!) I am no longer maintaining it. If you want to pursue that path, you can post on [this repo](https://github.com/expfactory/expfactory-python) and some of my colleagues might be able to help! I would also check that you are using the last released version (and not some older one). But you would want to install these in different places - if you try to install two modules with the same name (that are totally different) that would result in some weirdness I think! (E.g., an executable from one trying to use modules from the other).

For a simple solution, if you use the experiment statically, you wouldn't be able to specify a subject id associated with the data (the expfactory software manages that). You would want to do as @earcanal suggested and cd into the folder, start a webserver, 

```
cd n-back
python3 -m http.server 9999
```

Then what you would need to do is have participants finish, and then you download (and rename and move) the final result file. You know, the old school way :) (which actually even I did back in the days of working in a neuropsychology lab!) I am hoping you get the firewall issue worked out, and then can just use the easy container solution. I'm also very interested in this use case because many users have Windows machines.

**Comment by amclarekelly** [comment]
Hi @vsoch. Unfortunately turning off the firewall didn't help - I am still seeing "this site can't be reached." I've tried explorer, chrome, and firefox. Is it possible to use a different port? I'd like to try and help you figure this out if it's going to help future users - but then, who knows, maybe it's just that I have an old laptop running an old version of windows AND compulsory McAfee. Maybe you won't see these problems again!!

In good news - I can run n-back and digit span easily the way you and @earcanal suggested. Sorry - I hadn't appreciated how easy it was to run the experiments individually like that and just save the data. This will work for our purposes.

Please let me know if you'd like me to keep trying with docker.
Cheers,
Clare

**Comment by vsoch** [comment]
If you are happy, then I am too, and you are definitely welcome to close the issue.

**Comment by amclarekelly** [comment]
Thank you @vsoch, we can close it then. Wishing you all the best for your recovery!
