### ISSUE TITLE
Question: best way to resolve certbot permissions?

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#96]
Question on: https://www.github.com/expfactory/expfactory/tree/master/docs/pages/1-generate-https.md#step-3-get-certificates-with-certbot

I used `sudo`.

```
$ certbot certonly --nginx -d "${DOMAIN}" -d "www.${DOMAIN}" --email "${EMAIL}" --agree-tos --redirect
The following error was encountered:
[Errno 13] Permission denied: '/var/log/letsencrypt'
Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
```

**Comment by vsoch** [comment]
If you are a root user, then you wouldn't need to use sudo (and you would have the permission), and this is usually the case if working from a Docker container. If you aren't, then you need sudo for all edits to /var/log/letsencrypt. If you want to change permission you probably don't want to make it world writable, but you could do a chown for your user (or the user controlling lets encrypt):

```bash
sudo chown $USER -R /var/log/letsencrypt
```
I am more new to certbot, but this is probably just a permissions issue. You could ask @tylerburleigh who has used it quite a bit (and I think likely from a Docker container, which is why the sudo isn't there). @tylerburleigh should this be added to the docs, or a note that sudo is required if not in a container with it?

**Comment by vsoch** [comment]
Are you all set here @earcanal ?

**Comment by earcanal** [comment]
*I* am, but I had to modify the command to

`$ sudo certbot certonly --nginx -d "${DOMAIN}" --email "${EMAIL}" --agree-tos --redirect`

I think it's worth adding in the `sudo` or some words along the lines you wrote above.  I also don't have a `www` A record, so had to remove that `-d`.
